language: ruby

rvm:
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0
  - ruby-head
  - rbx-2
  - jruby-9.1.8.0
  - jruby-head

before_install:
  - gem update --system

env:
  global:
    - JRUBY_OPTS=--dev

script:
  - bundle exec rake ${TEST_SUITE:-test}

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
    - rvm: rbx-2
    - rvm: jruby-head
    - rvm: jruby-9.1.8.0
    - env: TEST_SUITE=templates:test
  include:
    - env: TEST_SUITE=templates:test
      rvm: 2.5.0
